# image will be published to ghcr.io/<user>/<name>
name: tsubas-ublue-nvidia
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/vauxite-nvidia
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - starship
      - papirus-icon-theme
      - neofetch
      - cockpit-bridge
      - cockpit-networkmanager
      - cockpit-pcp
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - podman-plugins
      - tailscale
      - btop
      - libadwaita
      - mesa-libGLU
      - google-noto-cjk-fonts
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles
      - ublue-os-wallpapers
      - ublue-update
      - dconf-update-service

  - type: yafti
    custom-flatpaks:

  - type: systemd
    system:
    enabled:
      - tailscaled.service

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
