# image will be published to ghcr.io/<user>/<name>
name: tsubas-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - starship
      - papirus-icon-theme
      - neofetch
      - podman-plugins
      - tailscale
      - btop
      - libadwaita
      - mesa-libGLU
      - easyeffects
      - google-noto-cjk-fonts
      - lsd
      - virt-install
      - virt-manager
      - virt-viewer
      - pavucontrol
      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-blur-my-shell
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles
      - ublue-os-wallpapers
      - ublue-update
      - dconf-update-service
      - gnome-vrr # enables gnome-vrr for your image
      - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      # - laptop # installs TLP and configures your system for laptop usage
      - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: yafti
    custom-flatpaks:

  - type: systemd
    system:
    enabled:
      - tailscaled.service

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
