title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to uBlue (Alpha, Adapted by Tsubajashi)"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.
  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome, Traveler!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features. This step will therefore remove all basic Fedora Flatpaks from your system! We will instead switch all core Flatpak applications over to the vastly superior, unfiltered Flathub. If you don't want to do this, simply exit this installer.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  configure-bazzite-arch:
    source: yafti.screen.package
    values:
      title: Setting up Bazzite Arch (This can take a long time)
      condition:
        run: grep -qvz "bazzite-arch" <<< $(distrobox list)
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:
        Install Bazzite Arch:
          description: Sets up a custom Arch Linux OCI in Distrobox that Steam, Lutris, and other gaming workloads will be run inside of.
          default: true
          packages:
          - Install Bazzite Arch: just --unstable install-bazzite-arch
  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
  check-user-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (User)
      condition:
        run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
      actions:
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        Core Apps:
          description: Core system applications for the GNOME desktop environment.
          default: true
          packages:
            - Camera: org.gnome.Snapshot
            - Firefox: org.mozilla.firefox
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Image Viewer: org.gnome.Loupe
            - Flatseal: com.github.tchx84.Flatseal
            - Clapper: com.github.rafostar.Clapper
            - G4Music: com.github.neithern.g4music
        Core Apps:
          description: Core Applications
          default: true
          packages:
        Gaming:
          description: "Rock and Stone!"
          default: true
          packages:
            - Bottles: com.usebottles.bottles
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Cartridges: hu.kramo.Cartridges
            - MangoHUD for most Flatpaks: org.freedesktop.Platform.VulkanLayer.MangoHud/23.08
            - MangoHUD for Steam: com.valvesoftware.Steam.Utility.MangoHud/x86_64/stable
            - MangoHUD for older Flatpaks: org.freedesktop.Platform.VulkanLayer.MangoHud/22.08
            - Proton Updater (GTK) for Steam: com.vysp3r.ProtonPlus
        Other Office Apps:
          description: Bow to Capitalism
          default: false
          packages:
            - Standard Notes: org.standardnotes.standardnotes
            - Thunderbird Email: org.mozilla.Thunderbird
        Streaming and Recording:
          description: Stream to the Internet
          default: false
          packages:
            - OBS Studio: com.obsproject.Studio
            - VkCapture for OBS: com.obsproject.Studio.Plugin.OBSVkCapture/x86_64/stable
            - VkCapture Support for newer Flatpaks: org.freedesktop.Platform.VulkanLayer.OBSVkCapture/x86_64/23.08
            - VkCapture Support for older Flatpaks: org.freedesktop.Platform.VulkanLayer.OBSVkCapture/x86_64/22.08
            - Gstreamer for OBS: com.obsproject.Studio.Plugin.Gstreamer
            - Gstreamer VAAPI for OBS: com.obsproject.Studio.Plugin.GStreamerVaapi
            - Boatswain for Streamdeck: com.feaneron.Boatswain
            - GPU Screen Recorder: com.dec05eba.gpu_screen_recorder
        Video/Audio Production:
          description: All the things you need to create your own content
          default: false
          packages:
            - Audacity: org.audacityteam.Audacity
            - Kdenlive: org.kde.kdenlive
            - Blender: org.blender.Blender
            - Aviator (AV1 Encoding GUI): net.natesales.Aviator
            - Video Trimmer: org.gnome.gitlab.YaLTeR.VideoTrimmer
        Music Streaming Services:
          description: For your Music Consumption needs.
          default: false
          packages:
            - Spotify: com.spotify.Client
            - Youtube Music: app.ytmdesktop.ytmdesktop
            - Apple Music: sh.cider.Cider
        Communication:
          description: Tools to communicate and collaborate
          default: true
          packages:
            - Discord: com.discordapp.Discord
            - Ferdium: org.ferdium.Ferdium
        Utilities:
          description: Useful Utilities
          default: true
          packages:
            - Video Downloader: com.github.unrud.VideoDownloader
            - Fragments (Torrent Manager): de.haeckerfelix.Fragments
            - Mission Center (Task Manager Alternative): io.missioncenter.MissionCenter
            - Gear Lever (AppImage Integrator): it.mijorus.gearlever
            - Identity: org.gnome.gitlab.YaLTeR.Identity
        Admin Tools:
          description: Helper Utilities for Administration
          default: false
          packages:
            - Cockpit Client: org.cockpit_project.CockpitClient
        Development Tools:
          description: Utilities for Development
          default: false
          packages:
            - VS Code: com.visualstudio.code

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying uBlue, we hope you enjoy it!
